config/routes.rb
    collection do
      get :product_convert
      get :show_convertion_details
      get :search_convertion
    end
  end
  get '/product_structures/convert/:id' => 'product_structures#convert_product'
  get '/product_structures/convertion/:id' => 'product_structures#convertion'
  get '/product_converts/' => 'product_structures#product_convert'
  post 'convert/:id' => 'product_structures#convert', :as => 'convert'

  resources :locations do
    collection do
      post :import
      get :add_sub_type
    end
  end

  resources :cancel_items do
    collection do
      get :search_receiving
    end
  end

  resources :purchase_return_details do
    collection do
      get :search_receiving
    end
  end

  resources :purchase_return_summaries do
    collection do
      get :search_receiving
    end
  end

  resources :purchase_summaries do
    collection do
      get :search_receiving
    end
  end

  resources :purchase_details do
    collection do
      get :search_receiving
    end
  end

  resources :staging_products do
    collection do
      get :get_selected_products
      get :sync_products
    end
  end

  get'product_mutation_history/' => 'product_mutation_history#index'
  get'product_mutation_history/:product_detail_id' => 'product_mutation_history#index'
  get'returns_to_warehouses/' => 'returns_to_hos#index'
  get'returns_to_warehouses/new' => 'returns_to_hos#new'
  get'returns_to_warehouses/edit' => 'returns_to_hos#edit'
  get'som/regenerate_mutation_history' => 'som#regenerate_mutation_history'
  get'som/importprevsales' => 'som#importprevsales'
  get'som/sc' => 'som#sc'
  get'custom' => 'som#custom'
  post'post_custom' => 'som#post_custom'

  get 'pb' => 'purchase_requests#pb'
  post 'pb' => 'purchase_requests#create_pb'

  resources :entity do

  end
  namespace :finance_reports do
    resources :bank_outs, only: :index do
      collection do
        get :export
      end
    end
    resources :cash_outs, only: :index do
      collection do
        get :export
      end
    end
    resources :global_finances, only: :index do
      collection do
        get :export
      end
    end
    resources :journal_memos, only: :index do
      collection do
        get :export
      end
    end
    resources :account_payables, only: :index do
      collection do
        get :export
      end
    end
    resources :store_cashs, only: :index do
      collection do
        get :export
      end
    end
    resources :receivables, only: :index do
      collection do
        get :export
      end
    end
    resources :repayments, only: :index do
      collection do
        get :export
      end
    end
    resources :denominations, only: :index do
      collection do
        get :export
      end
    end
  end

  namespace :finances do
    resources :cash_outs, only: [:new, :create, :show]
    resources :petty_cashes do
      collection do
        get :petty_cash_month
      end
    end
    resources :sod_eods
    resources :account_payables
    resources :account_receivables
    resources :forecasts do
      resources :monthly_forecasts
    end
    resources :budgetings
    resources :ap_invoices do
      collection do
        get :import
        get :add_ap_details
        get :select_receiving
        get :search_receivings
        get :get_receiving
      end
    end
  end
  get 'get_branches' => 'finances/petty_cashes#get_branches', :as => :get_branches

  namespace :finances do
    resources :petty_cash
  end

  resources :product_details do
    collection do
      get :get_product_details_modal
      get :search_product_details
      post :import
    end
  end
  resources :transaction_histories do
    collection do
      get :search
    end
  end

  resources :ar_vouchers do
    collection do
      get :add_payment
    end
  end

  resources :products do
    collection do
      get :get_products_modal
      get :search_products
      get :choose_product
      get :search_history
      get :stock
      get :m_history
      get :add_branch
      get :add_m_class
      get :autocomplete_goods_barcode
      get :mclass_per_department
      get :transaction_history
      post :import
    end
    member do
      get :print_to_pdf
      get :mutation_history
    end
  end

  resources :product_suppliers do
    collection do
      get :contact_people_per_supplier
      get :autocomplete_contact_person_name
      get :search_product_manual
    end
  end

  resources :edc_machines do
    collection do
      post :import
    end
  end
  resources :head_offices do
    collection do
      get :autocomplete_head_office_office_name
      get :branches_per_regional
      get :areas_per_branches
    end
  end

  resources :branches do
    collection do
      get :autocomplete_branch_office_name
      get :branches_per_regional
      get :areas_per_branches
      post :import
    end
  end

  resources :warehouses do
    collection do
      get :autocomplete_warehouse_office_name
      get :branches_per_regional
      get :areas_per_branches
    end
  end

  resources :vouchers
  resources :promos
  resources :stock_transfers do
    collection do
      get :search
      get :autocomplete_stock_transfer_name
      get :add_brand
      get :add_product
      get :get_last_number
    end
    member do
      get :print_to_pdf
    end
  end

  resources :planograms do
    resources :product_planograms
    collection do
      post :import
    end
  end

  resources :regionals do
    collection do
      post :import
      get :autocomplete_regional_name
    end
  end

  resources :cities do
    collection do
      post :import
      get :cities_per_regional
      get :autocomplete_city_name
    end
  end

  resources :areas do
    collection do
      post :import
      get :areas_per_cities
      get :branches_per_regional
      get :autocomplete_area_name
    end
  end

  resources :districts do
    collection do
      post :import
      get :autocomplete_districts_name
    end
  end

  resources :provinces do
    collection do
      post :import
      get :autocomplete_province_name
      get :provinces_per_regional
    end
  end

  resources :units do
    collection do
      get :autocomplete_unit_namepri
      post :import
    end
  end

  resources :price_tags do
    collection do
      get :print_to_pdf
      get :print_newest_product
      get :get_products_to_table
    end
    member do
      get :print_to_pdf
    end
  end

  resources :m_classes do
    collection do
      get :autocomplete_m_class_name
      get :add_sub_m_class
      post :import
    end
  end

  resources :product_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
      get :print_to_pdf
    end
    collection do
      get :add_product
    end
  end

  resources :product_transfer_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
    end
    collection do
      get :add_product
    end
  end

  resources :ads do
    collection do
      get :autocomplete_ad_url
      post :import
    end
  end
  resources :close_shifts do
    collection do
      get :tutup_shift
      get :save_income
      get :search_shift
    end
    member do
      get :print_to_pdf
    end
  end
  resources :month_ends do
    collection do
      get :report
    end
  end
  resources :colours do
    collection do
      get :autocomplete_colour_name
      post :import
    end
  end
  resources :planos do
    collection do
      get :autocomplete_plano_name
      get :get_planogram_type
      get :get_spd
      get :autogenerate_type
      get :generate_auto_pkm, as: 'generate_auto_pkm'
      post :import
    end
  end
  resources :pos_machines do
    collection do
      get :autocomplete_pos_machine_name
      post :import
    end
  end
  resources :selling_prices do
    collection do
      post :import
      get :search_product_manual
      get :search_in_modal
      get :fitur_filter
    end
  end
  resources :purchase_prices do
    collection do
      post :import
      get :search_product_manual
      get :search_in_modal
      get :fitur_filter
    end
  end

  resources :product_margins do
    collection do
      post :import
    end
  end

  resources :member_levels do
    collection do
      get :autocomplete_member_level_description
      post :import
    end
  end
  resources :to_do_lists do
    collection do
      post :import
    end
  end
  resources :promotions do
    collection do
      get :search
      get :autocomplete_promotion_name
      get :add_prize_list
      get :add_promo_item_list
      get :search_product_manual
      get :search_in_modal
      get :get_product
    end
  end

  resources :branch_prices

  resources :stock_opnames do
    collection do
      get :get_quantity_data
      get :start_stock_opname_data
      get :end_stock_opname_data
      get :select_stock_opname_data
      get :offices_per_rack
      get :rack_selected
    end
    member do
      get :print_to_pdf
      get :print_lkso
    end
  end

  resources :stock_opname_details do
    collection do
      post :import
    end
  end

  resources :members do
    collection do
      get :search
      get :discount
      post :create_member_discount
      post :import
      get '/edit_member_discount/:id' => 'members#edit_member_discount', as: :edit_member_discount
      put '/update_member_discount/:id' => 'members#update_member_discount', as: :update_member_discount
      delete '/delete_member_discount/:id' => 'members#delete_member_discount', as: :delete_member_discount
      put '/expired/:id' => 'members#expire', as: :expire
      get '/setting_point' => 'members#setting_point', as: :setting_point
      post 'create_setting_point' => 'members#create_setting_point', as: :create_setting_point
    end
  end

  resources :colours do
    collection do
      get :search
      get :autocomplete_colour_name
    end
  end

  resources :reorder_points do
    collection do
    end
  end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:destroy]
  autocomplete :branch, :office_name
  before_filter :can_view_branch, only: [:index, :show]
  before_filter :can_manage_branch, only: [:new, :create, :edit, :update, :destroy]

  def destroy
    @branch = Branch.find(params[:id])
    if @branch.check_transaction && @branch.destroy
      flash[:error] = nil
      flash[:notice] = "Successfully delete branch"
    else
      flash[:notice] = nil
      flash[:error] = "Can't delete branch. data in use"
    end
    get_paginated_branches
    respond_to do |format|
      format.js
    end
  end

  # POST /suppliers
  # POST /suppliers.json
  def update
    @branch = Branch.find(params[:id])
    office_departments = @branch.office_departments.map(&:id).join(', ')
    if @branch.update_attributes(branch_params.merge(head_office_id: (Branch.find_by_office_name(params[:branch2]).id rescue nil), province_id: (Province.find_by_name(params[:province]).id rescue nil)))
      @branch.office_departments.where("id IN (#{office_departments})").delete_all if office_departments.present?
      flash[:notice] = t(:successfully_updated)
      redirect_to branches_path
    else
      @regionals = Regional.all
      @head_offices = HeadOffice.all
      @users = User.all.map{|user|[user.username, user.id]}
      load_departments
      flash[:error] = @branch.errors.full_messages.join('<br/>')
      render "new"
    end
  end

  def edit
    @regionals = Regional.all
    @branch = Branch.find(params[:id])
    @head_offices = HeadOffice.all
    @users = User.all.map{|user|[user.username, user.id]}
    load_departments
  end

  def new
    @regionals = Regional.all
    @branch = Branch.new
    @users = User.joins(:role).limit(7).map{|user|[user.username, user.id]}
    @head_offices = HeadOffice.all
    load_departments
    respond_to do |format|
      format.html
    end
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @branch = Branch.new(
      branch_params.merge(
        head_office_id: (Branch.find_by_username(params[:branch2]).id rescue nil),
        code: ("#{('%03d' % ((Branch.last.code.gsub('M', '').to_i rescue 0)+1))}")
      )
    )
    @head_offices = HeadOffice.all
    @users = User.joins(:role).limit(7).map{|user|[user.username, user.id]}
    if @branch.save
      flash[:notice] = 'Store successfully created'
      redirect_to branches_path
    else
      @head_offices = HeadOffice.all
      @regionals = Regional.all
      @users = User.joins(:role).limit(7).map{|user|[user.username, user.id]}
      load_departments
      flash[:error] = @branch.errors.full_messages.join('<br/>')
      render "new"
    end
  end

  def index
    get_paginated_branches
    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.xls {
        filename = "Branch_#{Time.now.strftime("%Y-%m-%d %H:%M:%S")}.xls"
        send_data(@branches.to_xls, :type => "text/xls; charset=utf-8; header=present", :filename => filename)
      }
      format.json{
        render json: @branches.map{|branch|
          sales_sum = Sale.where("store_id=#{branch.id}").map(&:total_price).sum
          target_sec2015 = 10000000
          {
            office_name: branch.office_name, lat: branch.lat, long: branch.long, achievement: [(sales_sum/target_sec2015*100).round(2), 100].min, target_sec2015: target_sec2015,
              secsales: sales_sum
          }
        }.to_json
      }
      if(params[:a] == "a")
        format.csv {
          send_data(Branch.all.to_csv2, :filename => "Store.csv")
        }
      else
        format.csv {
          send_data(Branch.all.to_csv, :filename => "Store.csv")
        }
      end
    end
  end

  def import
    import_result = Branch.import(params[:file])
    if params[:file].present?
      if import_result[:error] == 1
        flash[:error] = import_result[:message]
      else
        flash[:notice] = import_result[:message]
      end
    else
      flash[:error] = "Please attach CSV File"
    end
    redirect_to branches_path
  end

  def show
    @branch = Branch.find(params[:id])
    @departments = @branch.departments
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def branches_per_regional
    @branches = City.where("regional_id=#{params[:regional_id]}").limit(11)
  end

  def areas_per_branches
    @areas = Area.where("regional_id=#{params[:regional_id]} AND city_id=#{params[:city_id]}").limit(11)
  end

  private
  def branch_params
    params.require(:branch).permit(
      :office_name, :description, :phone_number, :area, :address, :lat, :long,
      :regional, :email, :area, :province, :city, :districts, :zip_code, :rt,
      :rw, :village, :area_id, :province_id, :district_id, :city_id,
      :regional_id, :city_name, :city_name, :npwp, :is_active,
      office_departments_attributes: [:department_id]
    )
  end

  def can_view_branch
    not_authorized unless current_user.can_view_branch?
  end

  def can_manage_branch
    not_authorized unless current_user.can_manage_branch?
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_branch_list.html.erb
<% @branches.each_with_index do |branch, i| %>
  <tr>
    <td class="hidden-phone"><%= params[:page] ? (params[:page].to_i*10+i-9) : i+1 %></td>
    <td class="hidden-phone"><%= branch.code %></td>
    <td><%= link_to branch.office_name, branch_path(branch), class: 'blue' %></td>
    <td class="hidden-phone"><%= branch.area.name rescue '' %></td>
    <td class="hidden-phone"><%= branch.address %></td>
    <td class="hidden-phone"><%= branch.description %></td>
    <td class="nowrap">
      <%= link_to raw("<i class='fa fa-pencil'></i>"), edit_branch_path(branch), class: "btn btn-primary btn-xs custom-edit-btn" %>
      <%= link_to raw("<i class='fa fa-trash-o'></i>"), 'javascript:void(0)', onclick: "delete_one(#{branch.id}, 'branches')", class: "btn btn-danger btn-xs custom-edit-btn" %>
    </td>
  </tr>
<% end %>
<tr>
  <td colspan=11><!-- start pagination -->
    <% if @branches.present? %>
      <div class="dataTables_paginate paging_simple_numbers" id="dt_basic_paginate">
        <%= pagination_links(@branches, options = {}) %>
      </div>
    <% else %>
      <%= raw '<center>No Data Available</center>' %>
    <% end %>
  </td>
</tr>

app/views/branches/areas_per_branches.js.erb
<% if @areas %>
    $('#branch_area_id').html("<option value=''>Please Select</option><%= escape_javascript options_from_collection_for_select(@areas, :id, :name) %>");
<% end %>

app/views/branches/branches_per_regional.js.erb
<% if @branches %>
    $('#branch_city_id').html("<option value=''>Please Select</option><%= escape_javascript options_from_collection_for_select(@branches, :id, :name) %>");
<% end %>

app/views/branches/destroy.js.erb
$("#branch-list").html("<%= j(render 'branch_list') %>");
$('#notice_template').html("<%= j(render 'layouts/notice') %>")
paging()

app/views/branches/edit.html.erb
<%= render partial: 'form', locals: {label: 'Edit'} %>

app/views/branches/index.html.erb
<div id="ribbon"><!-- RIBBON -->
  <ol class="breadcrumb"><!-- breadcrumb -->
    <li>Master Data</li><li>Store</li><li>List</li>
  </ol><!-- end breadcrumb -->
</div><!-- END RIBBON -->
<div id="content"><!-- MAIN CONTENT -->
  <section id="widget-grid" class=""><!-- widget grid -->
    <div id='notice_template'><%= render 'layouts/notice' %></div>
    <div class="row"><!-- row -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><!-- NEW WIDGET START -->
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-1" data-widget-editbutton="false"><!-- Widget ID (each widget will need unique ID)-->
          <header id="header-product" role="heading">
          <h2><span class="widget-icon"> <i class="fa fa-list-ul"></i> </span> <%= t(:store_list) %></h2> <!-- header content --></header>
          <div><!-- widget div-->
            <div class="widget-body no-padding"><!-- widget content -->
              <%= link_to new_branch_url, :class => "btn btn-labeled btn-primary edit-btn-primary" do %>
                <span class="btn-label"><i class="glyphicon glyphicon-plus"></i></span><%= t(:add_store) %>
              <% end %>
              <ul id="myTab1" class="nav nav-tabs" style='margin: 20px 0 6px 6px; float: left'>
                <li class="dropdown">
                  <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i></button>
                  <ul class="dropdown-menu">
                    <li><%= link_to t(:export_to_csv), branches_path(:id => params[:id], format: "csv") %></li>
                    <li><%= link_to t(:export_to_excel), branches_path(:id => params[:id], format: "xls") %></li>
                    <li data-toggle="modal" data-target="#myModal" style='cursor: pointer'><a>Import from CSV</a></li>
                  </ul>
                </li>
              </ul>
            </div>
            <table class="table table-striped table-bordered" width="100%">
              <thead>
                <tr>
                  <th>No</th>
                  <th>
                    Code 
                    <span style="float: right;">
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'office_name-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'office_name-asc', class: 'sorting' %>
                  </span>
                  </th>
                  <th>
                    Name 
                    <span style="float: right;">
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'office_name-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'office_name-asc', class: 'sorting' %>
                  </span>
                  </th>
                  <th>
                    Area 
                    <span style="float: right;">
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'office_name-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'office_name-asc', class: 'sorting' %>
                  </span>
                  </th>
                  <th>
                    Address 
                    <span style="float: right;">
                    <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'description-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'description-asc', class: 'sorting' %>
                  </span>
                  </th>
                  <th>
                    Description 
                    <span style="float: right;">
                    <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'description-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'description-asc', class: 'sorting' %>
                  </span>
                  </th>
                  <th>Action</th>
                </tr>
                <tr>
                  <th></th>
                  <th class="hasinput"><%= text_field_tag :code, params[:code], class: 'form-control search', name: 'offices.code' %></th>
                  <th class="hasinput"><%= text_field_tag :office_name, params[:office_name], class: 'form-control search', name: 'offices.office_name' %></th>
                  <th class="hasinput"><%= text_field_tag :area, params[:area], class: 'form-control search', name: 'zones.name' %></th>
                  <th class="hasinput"><%= text_field_tag :address, params[:address], class: 'form-control search', name: 'offices.address' %></th>
                  <th class="hasinput"><%= text_field_tag :description, params[:description], class: 'form-control search', name: 'offices.description' %></th>
                  <th></th>
                </tr>
              </thead>
              <tbody id='branch-list'><%= render 'branch_list' %></tbody>
            </table>
          </div><!-- end widget -->
        </div><!-- end widget div -->
      </article><!-- WIDGET END -->
    </div><!-- end row -->
  </section><!-- end widget grid -->
</div><!-- end row -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Import Store</h4>
      </div>
      <%= form_tag import_branches_path(:id => params[:id]), multipart: true do %>
        <div class="modal-body">
          <%= file_field_tag :file, accept: ".csv", onchange: "checkfile(this);" %>
        </div>
        <div class="modal-footer">
          <%= link_to "Download Template", branches_path(format: "csv", :a => "a"), :class => "btn btn-success" %>
          <%= submit_tag "Import", :class => "btn btn-primary", :id => 'commit'%>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  window.reset = function (e) {
    e.wrap('<form>').closest('form').get(0).reset();
    e.unwrap();
  }
});
function checkfile(sender) {
    var validExts = new Array(".csv");
    var fileExt = sender.value;
    fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
    if (validExts.indexOf(fileExt) < 0) {
      alert("This is not a csv file");
      reset($("#file"));
      return false;
    }
    else return true;
};
</script>

app/views/branches/index.js.erb
$("#branch-list").html("<%= j(render 'branch_list') %>");
paging()

app/views/branches/new.html.erb
<%= render partial: 'form', locals: {label: 'Add'} %>

app/views/branches/show.html.erb
<script src="/js/jquery-2.1.1.min.js"></script><!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<div id="ribbon"><!-- RIBBON -->
  <ol class="breadcrumb"><!-- breadcrumb -->
    <li>Master Data</li><li>Store</li><li><%= @branch.office_name %></li>
  </ol><!-- end breadcrumb -->
</div><!-- END RIBBON -->
<div id="content"><!-- MAIN CONTENT -->
  <div class="row">
    <article class="col-sm-12 col-md-12"><!-- NEW COL START -->
      <div class="jarviswidget" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
        <header id="header-supplier">
          <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
          <h2><%= @branch.office_name %></h2>
        </header>
        <div><!-- widget div-->
          <div class="widget-body no-padding"><!-- widget content -->
            <%= form_for @branch, html: {class: "smart-form", id: "form-update-verify"} do |f| %>
              <fieldset> <!-- tambah supplier -->
                <div class="row">
                  <section class="col col-md-6">
                    <section class="form-group">
                      <label class="col-md-4 label">Code</label>
                      <label class="col-md-8 input custom-input-box"><%= @branch.code %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-4 label">Name</label>
                      <label class="col-md-8 textarea custom-input-box"><%= @branch.office_name %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-4 label">Regional</label>
                      <label class="col-md-8 input custom-input-box"><%= @branch.regional.name rescue '' %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-4 label">Branch</label>
                      <label class="col-md-8 input custom-input-box">
                        <%= @branch.city.name rescue '' %>
                      </label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-4 label">Area</label>
                      <label class="col-md-8 input custom-input-box">
                        <%= @branch.area.name rescue '' %>
                        </label>
                    </section><br>
                  </section>
                  <section class="col col-md-6">
                    <section class="form-group">
                      <label class="col-md-2 label">Telp. Number</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.phone_number %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">Email</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.email %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">Description</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.description %></label>
                    </section><br>
                  </section><br>
                </div>
              </fieldset>
              <fieldset>
                <section class="col col-md-6">
                  <section class="form-group">
                      <label class="col-md-2 label">Province</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.province %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">City</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.city_name %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">Districts</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.districts %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">Zip Code</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.zip_code %></label>
                    </section><br>
                </section>
                <section class="col col-md-6">
                  <section class="form-group">
                      <label class="col-md-2 label">Address</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.address %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">RT</label>
                      <label class="col-md-2 input custom-input-box"><%= @branch.rt %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">RW</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.rw %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">Village</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.village %></label>
                    </section><br>
                </section>
              </fieldset>
              <footer>
                <button type="button" class="btn btn-default" onclick="window.history.back();">Back</button>
              </footer>
            <% end %>
          </div>
        </div>
      </div>
    </article>
  </div>
</div>