config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :product_structures do
    collection do
      get :product_convert
      get :show_convertion_details
      get :search_convertion
    end
  end
  get '/product_structures/convert/:id' => 'product_structures#convert_product'
  get '/product_structures/convertion/:id' => 'product_structures#convertion'
  get '/product_converts/' => 'product_structures#product_convert'
  post 'convert/:id' => 'product_structures#convert', :as => 'convert'

  resources :locations do
    collection do
      post :import
      get :add_sub_type
    end
  end

  resources :cancel_items do
    collection do
      get :search_receiving
    end
  end

  resources :purchase_return_details do
    collection do
      get :search_receiving
    end
  end

  resources :purchase_return_summaries do
    collection do
      get :search_receiving
    end
  end

  resources :purchase_summaries do
    collection do
      get :search_receiving
    end
  end

  resources :purchase_details do
    collection do
      get :search_receiving
    end
  end

  resources :staging_products do
    collection do
      get :get_selected_products
      get :sync_products
    end
  end

  get'product_mutation_history/' => 'product_mutation_history#index'
  get'product_mutation_history/:product_detail_id' => 'product_mutation_history#index'
  get'returns_to_warehouses/' => 'returns_to_hos#index'
  get'returns_to_warehouses/new' => 'returns_to_hos#new'
  get'returns_to_warehouses/edit' => 'returns_to_hos#edit'
  get'som/regenerate_mutation_history' => 'som#regenerate_mutation_history'
  get'som/importprevsales' => 'som#importprevsales'
  get'som/sc' => 'som#sc'
  get'custom' => 'som#custom'
  post'post_custom' => 'som#post_custom'

  get 'pb' => 'purchase_requests#pb'
  post 'pb' => 'purchase_requests#create_pb'

  resources :entity do

  end
  namespace :finance_reports do
    resources :bank_outs, only: :index do
      collection do
        get :export
      end
    end
    resources :cash_outs, only: :index do
      collection do
        get :export
      end
    end
    resources :global_finances, only: :index do
      collection do
        get :export
      end
    end
    resources :journal_memos, only: :index do
      collection do
        get :export
      end
    end
    resources :account_payables, only: :index do
      collection do
        get :export
      end
    end
    resources :store_cashs, only: :index do
      collection do
        get :export
      end
    end
    resources :receivables, only: :index do
      collection do
        get :export
      end
    end
    resources :repayments, only: :index do
      collection do
        get :export
      end
    end
    resources :denominations, only: :index do
      collection do
        get :export
      end
    end
  end

  namespace :finances do
    resources :cash_outs, only: [:new, :create, :show]
    resources :petty_cashes do
      collection do
        get :petty_cash_month
      end
    end
    resources :sod_eods
    resources :account_payables
    resources :account_receivables
    resources :forecasts do
      resources :monthly_forecasts
    end
    resources :budgetings
    resources :ap_invoices do
      collection do
        get :import
        get :add_ap_details
        get :select_receiving
        get :search_receivings
        get :get_receiving
      end
    end
  end
  get 'get_branches' => 'finances/petty_cashes#get_branches', :as => :get_branches

  namespace :finances do
    resources :petty_cash
  end

  resources :product_details do
    collection do
      get :get_product_details_modal
      get :search_product_details
      post :import
    end
  end
  resources :transaction_histories do
    collection do
      get :search
    end
  end

  resources :ar_vouchers do
    collection do
      get :add_payment
    end
  end

  resources :products do
    collection do
      get :get_products_modal
      get :search_products
      get :choose_product
      get :search_history
      get :stock
      get :m_history
      get :add_branch
      get :add_m_class
      get :autocomplete_goods_barcode
      get :mclass_per_department
      get :transaction_history
      post :import
    end
    member do
      get :print_to_pdf
      get :mutation_history
    end
  end

  resources :product_suppliers do
    collection do
      get :contact_people_per_supplier
      get :autocomplete_contact_person_name
      get :search_product_manual
    end
  end

  resources :edc_machines do
    collection do
      post :import
    end
  end
  resources :head_offices do
    collection do
      get :autocomplete_head_office_office_name
      get :branches_per_regional
      get :areas_per_branches
    end
  end

  resources :branches do
    collection do
      get :autocomplete_branch_office_name
      get :branches_per_regional
      get :areas_per_branches
      post :import
    end
  end

  resources :warehouses do
    collection do
      get :autocomplete_warehouse_office_name
      get :branches_per_regional
      get :areas_per_branches
    end
  end

  resources :vouchers
  resources :promos
  resources :stock_transfers do
    collection do
      get :search
      get :autocomplete_stock_transfer_name
      get :add_brand
      get :add_product
      get :get_last_number
    end
    member do
      get :print_to_pdf
    end
  end

  resources :planograms do
    resources :product_planograms
    collection do
      post :import
    end
  end

  resources :regionals do
    collection do
      post :import
      get :autocomplete_regional_name
    end
  end

  resources :cities do
    collection do
      post :import
      get :cities_per_regional
      get :autocomplete_city_name
    end
  end

  resources :areas do
    collection do
      post :import
      get :areas_per_cities
      get :branches_per_regional
      get :autocomplete_area_name
    end
  end

  resources :districts do
    collection do
      post :import
      get :autocomplete_districts_name
    end
  end

  resources :provinces do
    collection do
      post :import
      get :autocomplete_province_name
      get :provinces_per_regional
    end
  end

  resources :units do
    collection do
      get :autocomplete_unit_namepri
      post :import
    end
  end

  resources :price_tags do
    collection do
      get :print_to_pdf
      get :print_newest_product
      get :get_products_to_table
    end
    member do
      get :print_to_pdf
    end
  end

  resources :m_classes do
    collection do
      get :autocomplete_m_class_name
      get :add_sub_m_class
      post :import
    end
  end

  resources :product_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
      get :print_to_pdf
    end
    collection do
      get :add_product
    end
  end

  resources :product_transfer_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
    end
    collection do
      get :add_product
    end
  end

  resources :ads do
    collection do
      get :autocomplete_ad_url
      post :import
    end
  end
  resources :close_shifts do
    collection do
      get :tutup_shift
      get :save_income
      get :search_shift
    end
    member do
      get :print_to_pdf
    end
  end
  resources :month_ends do
    collection do
      get :report
    end
  end
  resources :colours do
    collection do
      get :autocomplete_colour_name
      post :import
    end
  end
  resources :planos do
    collection do
      get :autocomplete_plano_name
      get :get_planogram_type
      get :get_spd
      get :autogenerate_type
      get :generate_auto_pkm, as: 'generate_auto_pkm'
      post :import
    end
  end
  resources :pos_machines do
    collection do
      get :autocomplete_pos_machine_name
      post :import
    end
  end
  resources :selling_prices do
    collection do
      post :import
      get :search_product_manual
      get :search_in_modal
      get :fitur_filter
    end
  end
  resources :purchase_prices do
    collection do
      post :import
      get :search_product_manual
      get :search_in_modal
      get :fitur_filter
    end
  end

  resources :product_margins do
    collection do
      post :import
    end
  end

  resources :member_levels do
    collection do
      get :autocomplete_member_level_description
      post :import
    end
  end
  resources :to_do_lists do
    collection do
      post :import
    end
  end
  resources :promotions do
    collection do
      get :search
      get :autocomplete_promotion_name
      get :add_prize_list
      get :add_promo_item_list
      get :search_product_manual
      get :search_in_modal
      get :get_product
    end
  end

  resources :branch_prices

  resources :stock_opnames do
    collection do
      get :get_quantity_data
      get :start_stock_opname_data
      get :end_stock_opname_data
      get :select_stock_opname_data
      get :offices_per_rack
      get :rack_selected
    end
    member do
      get :print_to_pdf
      get :print_lkso
    end
  end

  resources :stock_opname_details do
    collection do
      post :import
    end
  end

  resources :members do
    collection do
      get :search
      get :discount
      post :create_member_discount
      post :import
      get '/edit_member_discount/:id' => 'members#edit_member_discount', as: :edit_member_discount
      put '/update_member_discount/:id' => 'members#update_member_discount', as: :update_member_discount
      delete '/delete_member_discount/:id' => 'members#delete_member_discount', as: :delete_member_discount
      put '/expired/:id' => 'members#expire', as: :expire
      get '/setting_point' => 'members#setting_point', as: :setting_point
      post 'create_setting_point' => 'members#create_setting_point', as: :create_setting_point
    end
  end

  resources :colours do
    collection do
      get :search

app/models/transaction_history.rb
class TransactionHistory < ActiveRecord::Base
  has_many :transaction_history_details
end

app/controllers/transaction_histories_controller.rb
class TransactionHistoriesController < ApplicationController

  def index
    get_transaction_histories
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @transaction_history = Sale.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def search
    @transaction_histories = TransactionHistory.search(params[:search]).uniq.paginate(:page => params[:page], :per_page => 10) || []
    respond_to do |format|
      @transaction_history = TransactionHistory.new
      format.js
    end
  end

  def get_number
    @transaction_history_number = TransactionHistory.number(params)
    respond_to do |format|
      format.js
    end
  end

  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

private
  def get_transaction_histories
    conditions = []
    conditions << "updated_at >= '#{params[:last_update]}'" if params[:last_update].present?
    params[:search].each{|param|
      conditions << "LOWER(#{param[0]}) LIKE '%#{param[1]}%'"
    } if params[:search].present?
    @transaction_histories = Sale.where(conditions.join(' AND ')).order(default_order('sales')).paginate(:page => params[:page], :per_page => 10) || []
  end
end

app/views/transaction_histories/_transaction_history_list.html.erb
<% @transaction_histories.each_with_index do |transaction_history, i| %>
  <tr>
    <td class="hidden-phone"><%= params[:page] ? (params[:page].to_i*10+i-9) : i+1 %></td>
    <td><%= link_to transaction_history.code, transaction_history_path(transaction_history), class: 'blue' %></td>
    <td><%= transaction_history.transaction_date %></td>
    <td><%= transaction_history.member.name rescue '-' %></td>
    <td><%= transaction_history.total_quantity %></td>
    <td><%= format_currency transaction_history.total_price %></td>
    <td><%= format_currency transaction_history.total_paid  %></td>
    <td><%= format_currency transaction_history.exchange %></td>
    <td><%= format_currency transaction_history.total_outstanding %></td>
  </tr>
<% end %>
<tr>
  <td colspan=9>
    <% if @transaction_histories.present? %>
      <div class="dataTables_paginate paging_simple_numbers" id="dt_basic_paginate">
        <%= pagination_links(@transaction_histories, options = {}) %>
      </div>
    <% else %>
      <%= raw '<center>No Data Available</center>' %>
    <% end %>
  </td>
</tr>

app/views/transaction_histories/index.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<div id="ribbon"><!-- RIBBON -->
  <ol class="breadcrumb"><!-- breadcrumb -->
    <li>Transaction </li><li>Transaction History</li><li>List</li>
  </ol><!-- end breadcrumb -->
</div><!-- END RIBBON -->
<div id="content"><!-- MAIN CONTENT -->
  <section id="widget-grid" class=""><!-- widget grid -->
    <div id="notice_template"><%= render 'layouts/notice' %></div>
    <div class="row"><!-- row -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><!-- NEW WIDGET START -->
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-1" data-widget-editbutton="false"><!-- Widget ID (each widget will need unique ID)-->
          <header id="header-product" role="heading">
          <h2><span class="widget-icon"> <i class="fa fa-list-ul"></i> </span> Transaction History</h2> <!-- header content --></header>
          <div><!-- widget div-->
            
            <table class="table table-striped table-bordered" width="100%">
              <thead>
                <tr>
                  <th>No</th>
                  <th>
                    Transaction No 
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'transaction_no-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'transaction_no-asc', class: 'sorting' %>
                    </span>
                  </th>
                  <th>
                    Date
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'name-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'name-asc', class: 'sorting' %>
                    </span>
                  </th>
                  <th>
                    Customer Name
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'name-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'name-asc', class: 'sorting' %>
                    </span>
                  </th>
                  <th>
                    Item QTY
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'name-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'name-asc', class: 'sorting' %>
                    </span>
                  </th>
                  <th>
                    Transaction Amount
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'name-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'name-asc', class: 'sorting' %>
                    </span>
                  </th>
                  <th>
                    Total Paid
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'name-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'name-asc', class: 'sorting' %>
                    </span>
                  </th>
                  <th>
                    Exchange
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'name-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'name-asc', class: 'sorting' %>
                    </span>
                  </th>
                  <th>
                    Outstanding
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'name-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'name-asc', class: 'sorting' %>
                    </span>
                  </th>
                  </tr>
                  <tr>
                    <th></th>
                    <th class="hasinput"><%= text_field_tag :transaction_no, params[:transaction_no], class: 'form-control search' %></th>
                    <th class="hasinput"><%= text_field_tag :date, params[:date], class: 'form-control search', name: "to_char(transaction_histories.date, 'DD-MM-YYYY')" %></th>
                    <th class="hasinput"><%= text_field_tag :customer_name, params[:customer_name], class: 'form-control search' %></th>
                    <th class="hasinput"><%= text_field_tag :item_qty, params[:item_qty], class: 'form-control search', name: "to_char(transaction_histories.item_qty, '99999999D99')" %></th>
                    <th class="hasinput"><%= text_field_tag :transaction_amount, params[:transaction_amount], class: 'form-control search', name: "to_char(transaction_histories.transaction_amount, '99999999D99')" %></th>
                    <th class="hasinput"><%= text_field_tag :total_paid, params[:total_paid], class: 'form-control search', name: "to_char(transaction_histories.total_paid, '99999999D99')" %></th>
                    <th class="hasinput"><%= text_field_tag :exchange, params[:exchange], class: 'form-control search', name: "to_char(transaction_histories.exchange, '99999999D99')" %></th>
                    <th class="hasinput"><%= text_field_tag :outstanding, params[:outstanding], class: 'form-control search', name: "to_char(transaction_histories.outstanding, '99999999D99')" %></th>
                  </tr>
                </thead>
                <tbody id='transaction_history-list'><%= render 'transaction_history_list' %></tbody>
              </table>
          </div><!-- end widget -->
        </div><!-- end widget div -->
      </article><!-- WIDGET END -->
    </div>  <!-- end row -->
  </section><!-- end widget grid -->
</div>  <!-- end row -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Import Unit</h4>
      </div>
      <div class="modal-body">
        <%= form_tag import_units_path(:id => params[:id]), multipart: true do %>
          <%= file_field_tag :file %>
      </div>
      <div class="modal-footer">
        <%= link_to "Download Template", units_path(format: "csv", :a => "a"), :class => "btn btn-success" %>
        <%= submit_tag "Import", :class => "btn btn-primary", id: "commit"%>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $('#commit').bind("click",function(){ 
    if(!$('#file').val()){
      alert("File not been chosen");
      return false;
    }
  }); 
});
</script>

app/views/transaction_histories/index.js.erb
$("#transaction_history-list").html("<%= j(render 'transaction_history_list') %>");
paging()

app/views/transaction_histories/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Code</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
      </Row>
    <% Transaction History.all.each do |transaction_history| %>
      <Row>
        <Cell><Data ss:Type="String"><%= transaction_history.code %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transaction_history.name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/transaction_histories/search.js.erb
$("#transaction_history-list").html("<%= j(render 'transaction_history_list') %>");
$("#form-transaction_history").html("<%= j(render 'form') %>");

app/views/transaction_histories/show.html.erb
<script src="/js/jquery.min.js"></script>
<div id="ribbon">
  <ol class="breadcrumb">
    <li>Master Data</li><li>Transaction History</li><li><%= @transaction_history.code %></li>
  </ol>
</div>
<div id="content">
  <div class="row">
    <article class="col-sm-12 col-md-12">
      <div class="jarviswidget" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
        <header id="header-supplier">
          <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
          <h2><%= @transaction_history.code %></h2>
        </header>
        <div>
          <div class="widget-body no-padding">
              <h3>
                Transaction Detail
              </h3>
              <fieldset>
                <div class="row">
                  <section class="col col-md-6">
                    <section>
                      <label class="col-md-3">Transaction No</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @transaction_history.code %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3">Date</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @transaction_history.created_at.to_date %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3">Customer Name</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @transaction_history.member.name rescue '-' %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3">Item Qty</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @transaction_history.total_quantity %>
                      </label>
                    </section><br>
                    </section>
                    <section class ="col col-md-6">
                    <section>
                      <label class="col-md-3">Amount</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= number_to_currency(@transaction_history.total_price, locale: :id)   %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3">Total Paid</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= number_to_currency(@transaction_history.total_paid, locale: :id)   %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3">Exchange</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= number_to_currency(@transaction_history.exchange, locale: :id)   %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3">Outstanding</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= number_to_currency(@transaction_history.total_outstanding, locale: :id)   %>
                      </label>
                    </section><br>
                  </section> <br>
                </div>
                </fieldset>
                <h3>
                  Member Detail
                </h3>
                <fieldset>
                <div class="row">
                  <% @member = Member.find_by_name(@transaction_history.member.name) rescue ''%>
                  <section class="col col-md-6">
                    <section>
                      <label class="col-md-3 ">Member Code</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @member.code rescue '' %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3 ">ID Card</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @member.card_number rescue '' %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3 ">Name</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @member.name rescue '' %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3 ">Date Lahir</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @member.birthday rescue '' %>
                      </label>
                    </section><br>
                    </section>
                    <section class ="col col-md-6">
                    <section>
                      <label class="col-md-3 ">Address</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @member.address rescue '' %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3 ">HP</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @member.hp rescue '' %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3 ">Email</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @member.email rescue '' %>
                      </label>
                    </section><br>
                    <section>
                      <label class="col-md-3 ">Gender</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @member.gender rescue '' %>
                      </label>
                    </section><br>
                  </section>
                </div>
              </fieldset><br>
              <h2>Table</h2>
              <fieldset>
                <div class="row">
                  <table class="table table-striped table-brequested table-hover" width="100%" id="request">
                    <thead>
                      <tr>
                        <th>CODE</th>
                        <th>BRAND</th>
                        <th>TYPE</th>
                        <th>ARTICLE</th>
                        <th>COLOUR</th>
                        <th>SIZE</th>
                        <th>QUANTITY</th>
                        <th>TOTAL PRICE</th>
                        <th>TOTAL DISCOUNT</th>
                      </tr>
                    </thead>
                    <tbody>
                      <%# @transaction_history.transaction_history_details.group_by{|prd|prd.product_size.product_id}.each do |prd| %>
                      <% @transaction_history.sales_details.each do |prd| %>
                        <%#detail = prd[1][0].product_size %>
                        <%#product = detail.product %>
                        <tr>
                          <td><%= prd.product.barcode rescue ''%></td>
                          <td><%= prd.product.brand.name rescue '' %></td>
                          <td><%= prd.product.m_class.name rescue '' %></td>
                          <td><%= prd.product.article rescue '' %></td>
                          <td><%= prd.product.colour.name rescue '' %></td>
                          <td><%= prd.product.size.description rescue '' %></td>
                          <td><%= prd.quantity rescue '' %></td>
                          <td><%= number_to_currency(prd.total_price, locale: :id) rescue ''%></td>
                          <td><%= number_to_percentage(prd.discount, precision: 0) rescue '' %></td>
                          <td></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </fieldset>

              <footer>
                <button type="button" class="btn btn-default" onclick="window.history.back();">Back</button>
              </footer>

          </div>
        </div>
      </div>
    </article>
  </div>
</div>