config/routes.rb
    resources :cash_outs, only: [:new, :create, :show]
    resources :petty_cashes do
      collection do
        get :petty_cash_month
      end
    end
    resources :sod_eods
    resources :account_payables
    resources :account_receivables
    resources :forecasts do
      resources :monthly_forecasts
    end
    resources :budgetings
    resources :ap_invoices do
      collection do
        get :import
        get :add_ap_details
        get :select_receiving
        get :search_receivings
        get :get_receiving
      end
    end
  end
  get 'get_branches' => 'finances/petty_cashes#get_branches', :as => :get_branches

  namespace :finances do
    resources :petty_cash
  end

  resources :product_details do
    collection do
      get :get_product_details_modal
      get :search_product_details
      post :import
    end
  end
  resources :transaction_histories do
    collection do
      get :search
    end
  end

  resources :ar_vouchers do
    collection do
      get :add_payment
    end
  end

  resources :products do
    collection do
      get :get_products_modal
      get :search_products
      get :choose_product
      get :search_history
      get :stock
      get :m_history
      get :add_branch
      get :add_m_class
      get :autocomplete_goods_barcode
      get :mclass_per_department
      get :transaction_history
      post :import
    end
    member do
      get :print_to_pdf
      get :mutation_history
    end
  end

  resources :product_suppliers do
    collection do
      get :contact_people_per_supplier
      get :autocomplete_contact_person_name
      get :search_product_manual
    end
  end

  resources :edc_machines do
    collection do
      post :import
    end
  end
  resources :head_offices do
    collection do
      get :autocomplete_head_office_office_name
      get :branches_per_regional
      get :areas_per_branches
    end
  end

  resources :branches do
    collection do
      get :autocomplete_branch_office_name
      get :branches_per_regional
      get :areas_per_branches
      post :import
    end
  end

  resources :warehouses do
    collection do
      get :autocomplete_warehouse_office_name
      get :branches_per_regional
      get :areas_per_branches
    end
  end

  resources :vouchers
  resources :promos
  resources :stock_transfers do
    collection do
      get :search
      get :autocomplete_stock_transfer_name
      get :add_brand
      get :add_product
      get :get_last_number
    end
    member do
      get :print_to_pdf
    end
  end

  resources :planograms do
    resources :product_planograms
    collection do
      post :import
    end
  end

  resources :regionals do
    collection do
      post :import
      get :autocomplete_regional_name
    end
  end

  resources :cities do
    collection do
      post :import
      get :cities_per_regional
      get :autocomplete_city_name
    end
  end

  resources :areas do
    collection do
      post :import
      get :areas_per_cities
      get :branches_per_regional
      get :autocomplete_area_name
    end
  end

  resources :districts do
    collection do
      post :import
      get :autocomplete_districts_name
    end
  end

  resources :provinces do
    collection do
      post :import
      get :autocomplete_province_name
      get :provinces_per_regional
    end
  end

  resources :units do
    collection do
      get :autocomplete_unit_namepri
      post :import
    end
  end

  resources :price_tags do
    collection do
      get :print_to_pdf
      get :print_newest_product
      get :get_products_to_table
    end
    member do
      get :print_to_pdf
    end
  end

  resources :m_classes do
    collection do
      get :autocomplete_m_class_name
      get :add_sub_m_class
      post :import
    end
  end

  resources :product_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
      get :print_to_pdf
    end
    collection do
      get :add_product
    end
  end

  resources :product_transfer_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
    end
    collection do
      get :add_product
    end
  end

  resources :ads do
    collection do
      get :autocomplete_ad_url
      post :import
    end
  end
  resources :close_shifts do
    collection do
      get :tutup_shift
      get :save_income
      get :search_shift
    end
    member do
      get :print_to_pdf
    end
  end
  resources :month_ends do
    collection do
      get :report
    end
  end
  resources :colours do
    collection do
      get :autocomplete_colour_name
      post :import
    end
  end
  resources :planos do
    collection do
      get :autocomplete_plano_name
      get :get_planogram_type
      get :get_spd
      get :autogenerate_type
      get :generate_auto_pkm, as: 'generate_auto_pkm'
      post :import
    end
  end
  resources :pos_machines do
    collection do
      get :autocomplete_pos_machine_name
      post :import
    end
  end
  resources :selling_prices do
    collection do
      post :import
      get :search_product_manual
      get :search_in_modal
      get :fitur_filter
    end
  end
  resources :purchase_prices do
    collection do
      post :import
      get :search_product_manual
      get :search_in_modal
      get :fitur_filter
    end
  end

  resources :product_margins do
    collection do
      post :import
    end
  end

  resources :member_levels do
    collection do
      get :autocomplete_member_level_description
      post :import
    end
  end
  resources :to_do_lists do
    collection do
      post :import
    end
  end
  resources :promotions do
    collection do
      get :search
      get :autocomplete_promotion_name
      get :add_prize_list
      get :add_promo_item_list
      get :search_product_manual
      get :search_in_modal
      get :get_product
    end
  end

  resources :branch_prices

  resources :stock_opnames do
    collection do
      get :get_quantity_data
      get :start_stock_opname_data
      get :end_stock_opname_data
      get :select_stock_opname_data
      get :offices_per_rack
      get :rack_selected
    end
    member do
      get :print_to_pdf
      get :print_lkso
    end
  end

  resources :stock_opname_details do
    collection do
      post :import
    end
  end

  resources :members do
    collection do
      get :search
      get :discount
      post :create_member_discount
      post :import
      get '/edit_member_discount/:id' => 'members#edit_member_discount', as: :edit_member_discount
      put '/update_member_discount/:id' => 'members#update_member_discount', as: :update_member_discount
      delete '/delete_member_discount/:id' => 'members#delete_member_discount', as: :delete_member_discount
      put '/expired/:id' => 'members#expire', as: :expire
      get '/setting_point' => 'members#setting_point', as: :setting_point
      post 'create_setting_point' => 'members#create_setting_point', as: :create_setting_point
    end
  end

  resources :colours do
    collection do
      get :search
      get :autocomplete_colour_name
    end
  end

  resources :reorder_points do
    collection do
    end
  end

  resources :safety_stocks do
    collection do
    end
  end

  resources :out_stocks do
    collection do
      get :search
      get :autocomplete_out_stock_name
    end
  end

  resources :min_stocks do
    collection do
      get :search
      get :autocomplete_min_stock_name
    end
  end

  resources :price_histories do
    collection do
      get :search
    end
  end

  resources :good_transfers do
    member do
      get :print_to_pdf
    end
    collection do
      get :search
      get :autocomplete_good_transfer_code
      get :get_product
      get :add_brand
      get :add_product
      get :get_last_number
      get :get_template
      post :import
    end
  end

  resources :departments do
    collection do
      get :search
      get :autocomplete_department_name
      get :departments_per_supplier
      post :import
      get :departments_list
      get :categories_per_department
    end
  end

  resources :brands do
    collection do
      get :search
      get :autocomplete_brand_name
      post :import
      get :brands_per_supplier
      get :generate_data_brand
    end
  end

  resources :suppliers do
    collection do
      get :get_suppliers_modal
      get :search_supplier
      get :get_number
      get :search
      get :autocomplete_supplier_name
      get :autocomplete_supplier_code
      post :import
      get :add_contact
      get :add_bank_account
    end
  end

  resources :sizes do
    collection do
      get :search
      get :autocomplete_size_name
      get :generate_details
    end
  end

  resources :types do
    collection do
      get :search
      get :autocomplete_type_name
      get 'detail_sub_type/:id' => "types#detail_sub_type", as: :detail_sub_type
      get 'new_sub_type/:id' => "types#new_sub_type", as: :new_sub_type
    end
  end

  devise_for :users
  resources :users do
    collection do
      get :autocomplete_name
    end
    member do
      get :change_password
      patch :post_change_password
    end
  end
  resources :user_profiles do
    member do
      patch :update_profile
    end
  end

  resources :companyprofile do

  end

  resources :organizations do
    member do
      get :position_edit
    end
    collection do
      get :search
      get :posisision_data
      get :position_index
      post :position_index
      get :position_show
      get :position_new
      post :position_create
      delete :position_destroy
      patch :position_update
      put :position_update

    end
  end

   resources :positions

  resources :fingerprints do
    collection do
      get :search
    end
  end

  resources :companies do
    collection do
      get :get_city
    end
  end

  resources :roles do
    collection do
      post :import
    end
  end

  resources :approvals

app/models/unit.rb
class Unit < ActiveRecord::Base
  before_validation :upcase_save

  validates :name, :short_name, presence: {message: 'required'}, :uniqueness => {:case_sensitive => false}
  validates_format_of :name, :with => /^[a-zA-Z\d\s]*$/i, :multiline => true, :message => "alphanumeric input only"
  validates_format_of :short_name, :with => /^[a-zA-Z\d\s]*$/i, :multiline => true, :message => "alphanumeric input only"

  def check_transaction
    return false if Product.find_by_unit_id(self.id)
    true
  end

  def upcase_save
    self.name = name.titleize rescue nil
    self.short_name = short_name.titleize rescue nil
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ["name", "short_name"]
      all.each do |unit|
        csv << [unit.name, unit.short_name]
      end
    end
  end

  def self.to_csv2(options = {})
    CSV.generate(options) do |csv|
      csv << ["name", "short_name"]
    end
  end

  def self.import(file)
    line = 0
    CSV.foreach(file.path, headers: true) do |row|
      if find_by_name(row["name"].upcase).nil?
        parameters = ActionController::Parameters.new(row.to_hash)
        unit = new(parameters.permit(:name, :short_name))
        unless unit.save
          return {error: 1, message: line == 0 ? "Import failed, please recheck CSV file. #{unit.errors.full_messages.join('<br/>')}" : "Successfully imported until line #{line}. Failed imported  from line #{line+1}. Please recheck and reupload from line #{line+1}. #{unit.errors.full_messages.join('<br/>')}"}
        end
        line += 1
      else
        return {error: 0, message: "Successfully imported until line #{line}. Failed imported  from line #{line+1}. Must unique"}
      end
    end
    return {error: 0, message: "Successfully imported"}
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:destroy]
  autocomplete :unit, :name
  before_action :set_unit, only: [:show, :destroy, :edit, :update]
  before_filter :can_view_unit, only: [:index, :show]
  before_filter :can_manage_unit, only: [:new, :create, :edit, :update, :destroy]

  def index
    get_paginated_units
    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.xls {
        filename = "Unit_#{Time.now.strftime("%Y-%m-%d %H:%M:%S")}.xls"
      }
      if(params[:a] == "a")
        format.csv { send_data Unit.all.to_csv2 }
      else
        format.csv { send_data Unit.all.to_csv }
      end
    end
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def import
    import_result = Unit.import(params[:file])
    if %w(text/csv application/vnd.ms-excel).include?params[:file].content_type
      if import_result[:error] == 1
        flash[:error] = import_result[:message]
      else
        flash[:notice] = import_result[:message]
      end
    else
      flash[:error] = "Please attach CSV File"
    end
    redirect_to units_path
  end

  def new
    @unit = Unit.new(params[:unit])
    respond_to do |format|
      format.html
    end
  end

  def create
    @unit = Unit.new(unit_params)
    respond_to do |format|
      if @unit.save
        flash[:notice] = 'Unit was successfully created.'
        format.html{redirect_to units_path}
      else
        flash[:error] = @unit.errors.full_messages.join('</br>')
        format.html{render "new"}
      end
    end
  end

  def edit
    @unit = Unit.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def update
    @unit = Unit.find(params[:id])
    if @unit.update_attributes(unit_params)
      flash[:notice] = 'Unit was successfully updated.'
      redirect_to units_path
    else
      flash[:error] = @unit.errors.full_messages
      render "edit"
    end
  end

  def destroy
    if @unit.check_transaction && @unit.destroy
      flash[:error] = nil
      flash[:notice] = "Successfully delete unit"
    else
      flash[:notice] = nil
      flash[:error] = "Can't delete unit. data in use"
    end
    get_paginated_units
    respond_to do |format|
      format.js
    end
  end

  private
  def get_paginated_units
    conditions = []
    params[:search].each{|param|
      conditions << "LOWER(#{param[0]}) LIKE '%#{param[1]}%'"
    } if params[:search].present?
    @units = Unit.where(conditions.join(' AND ')).order(default_order('units')).paginate(page: params[:page], per_page: 10) || []
  end

  def unit_params
    params.require(:unit).permit(:name, :short_name)
  end

  def can_view_unit
    not_authorized unless current_user.can_view_unit?
  end

  def can_manage_unit
    not_authorized unless current_user.can_manage_unit?
  end

  def set_unit
    @unit = Unit.find(params[:id])
  end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<div id="ribbon"><!-- RIBBON -->
  <ol class="breadcrumb"><!-- breadcrumb -->
    <li><%= t(:data_master) %></li><li><%= t(:unit) %></li><li><%= label %></li>
  </ol><!-- end breadcrumb -->
</div><!-- END RIBBON -->
<div id="content"><!-- MAIN CONTENT -->
  <div class="row">
    <article class="col-sm-12 col-md-12"><!-- NEW COL START -->
      <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
        <header id="header-unit">
          <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
          <h2><%= label %> <%= t(:unit) %></h2>
        </header>
        <div><!-- widget div-->
          <div class="widget-body no-padding"><!-- widget content -->
            <%= form_for @unit, html: {class: "smart-form", id: "form-update-verify"} do |f| %>
              <fieldset>
                <div class="row">
                  <section class="col col-md-6">
                    <section>
                      <label class="label col-md-3"><%= t(:unit_name) %> <span class='important'>*</span></label>
                      <label class="input col-md-9 custom-input-box"><%= f.text_field :name, class: "input-sm #{(error_field @unit, :name)}" %></label>
                    </section>
                    <section>
                      <label class="label col-md-3"><%= t(:short_name) %> <span class='important'>*</span></label>
                      <label class="input col-md-9 custom-input-box"><%= f.text_field :short_name, :class => "input-sm #{(error_field @unit, :short_name)}" %></label>
                    </section>
                  </section>
                </div> <!-- row -->
              </fieldset>
              <footer>
                <input class="btn btn-primary" type="submit" value="Submit"/>
                <button type="button" class="btn btn-default" onclick="window.history.back();">
                  Back
                </button>
              </footer>
            <% end %>
          </div><!-- end widget content -->
        </div><!-- end widget div -->
      </div><!-- end widget -->
    </article><!-- END COL -->
  </div><!-- end widget div -->
</div><!-- end widget div -->

<SCRIPT>
  $('form').submit(function() {
    $('input.btn-primary').prop("disabled", "disabled");
  })
</SCRIPT>

app/views/units/_unit_list.html.erb
<% @units.each_with_index do |unit, i| %>
  <tr>
    <td class="hidden-phone"><%= params[:page] ? (params[:page].to_i*10+i-9) : i+1 %></td>
    <td><%= link_to unit.name, unit_path(unit), class: 'blue' %></td>
    <td class="hidden-phone"><%= unit.short_name %></td>
    <td class="hidden-phone">
      <%= link_to edit_unit_path(unit), class: "btn btn-primary btn-xs edit-btn-dlt" do %>
        <i class="fa fa-pencil"></i>
      <% end %>
      <%= link_to 'javascript:void(0)', onclick: "delete_one(#{unit.id}, 'units')", class: "btn btn-danger btn-xs edit-btn-dlt" do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
    </td>
  </tr>
<% end %>
<tr>
  <td colspan=4><!-- start pagination -->
    <div class="dataTables_paginate paging_simple_numbers" id="dt_basic_paginate">
      <%= pagination_links(@units, options = {}) %>
    </div>
  </td>
</tr>

app/views/units/create.js.erb
$("#notification").html("<%= j(render 'dashboard/notification') %>");
<% if @unit.errors.blank? %>
  $("#unit-list").html("<%= j(render 'unit_list') %>");
<% end %>
$("#form-unit").html("<%= j(render 'form') %>");

app/views/units/destroy.js.erb
$("#unit-list").html("<%= j(render 'unit_list') %>");
paging()
$("#notice_template").html("<%= j(render 'layouts/notice') %>");

app/views/units/edit.html.erb
<%= render partial: 'form', locals: {label: 'Edit'} %>

app/views/units/edit.js.erb
$("#form-unit").html("<%= j(render 'form') %>");

app/views/units/index.html.erb
<link rel="stylesheet" href="/css/jquery-ui.css">
<script src="/js/jquery-1.10.2.js"></script>
<script src="/js/jquery-ui.js"></script>
<div id="ribbon"><!-- RIBBON -->
  <ol class="breadcrumb"><!-- breadcrumb -->
    <li>Master Data</li><li><%= t(:unit_of_measure) %></li><li>List</li>
  </ol><!-- end breadcrumb -->
</div><!-- END RIBBON -->
<div id="content"><!-- MAIN CONTENT -->
  <section id="widget-grid" class=""><!-- widget grid -->
    <div id="notice_template"><%= render 'layouts/notice' %></div>
    <div class="row"><!-- row -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><!-- NEW WIDGET START -->
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-1" data-widget-editbutton="false"><!-- Widget ID (each widget will need unique ID)-->
          <header id="header-product" role="heading">
          <h2><span class="widget-icon"> <i class="fa fa-list-ul"></i> </span> <%= t(:unit_of_measure_list) %></h2> <!-- header content --></header>
          <div><!-- widget div-->
            <div class="widget-body no-padding"><!-- widget content -->
              <%= link_to new_unit_url, :class => "btn btn-labeled btn-primary edit-btn-primary" do %>
                <span class="btn-label"><i class="glyphicon glyphicon-plus"></i></span><%= t(:add_unit_of_measure) %>
              <% end %>
              <ul id="myTab1" class="nav nav-tabs" style='margin: 20px 0 6px 6px; float: left'>
                <li class="dropdown">
                  <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i></button>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Export to CSV",  units_path(:id => params[:id], format: "csv") %></li>
                    <li><%= link_to "Export to Excel", units_path(:id => params[:id], format: "xls") %></li>
                    <li data-toggle="modal" data-target="#myModal" style='cursor: pointer'><a>Import from CSV</a></li>
                  </ul>
                </li>
              </ul>
            </div>
            <table class="table table-striped table-bordered" width="100%">
              <thead>
                <tr>
                  <th>No</th>
                  <th>
                    Name
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'name-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'name-asc', class: 'sorting' %>
                    </span>
                  </th>
                  <th>
                    Abbreviation
                  <span style="float: right;">
                    <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'short_name-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'short_name-asc', class: 'sorting' %>
                    </span>
                  </th>
                  <th class="col-md-2">Action</th>
                </tr>
                <tr>
                  <th></th>
                  <th class="hasinput"><%= text_field_tag :name, params[:name], class: 'form-control search' %></th>
                  <th class="hasinput"><%= text_field_tag :short_name, params[:short_name], class: 'form-control search' %></th>
                  <th></th>
                </tr>
              </thead>
              <tbody id='unit-list'><%= render 'unit_list' %></tbody>
            </table>
          </div><!-- end widget -->
        </div><!-- end widget div -->
      </article><!-- WIDGET END -->
    </div>	<!-- end row -->
  </section><!-- end widget grid -->
</div>	<!-- end row -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Import Unit</h4>
      </div>
      <div class="modal-body">
        <%= form_tag import_units_path(:id => params[:id]), multipart: true do %>
          <%= file_field_tag :file %>
      </div>
      <div class="modal-footer">
        <%= link_to "Download Template", units_path(format: "csv", :a => "a"), :class => "btn btn-success" %>
        <%= submit_tag "Import", :class => "btn btn-primary", id: "commit"%>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $('#commit').bind("click",function(){ 
    if(!$('#file').val()){
      alert("File not been chosen");
      return false;
    }
  }); 
});
</script>

app/views/units/index.js.erb
$("#unit-list").html("<%= j(render 'unit_list') %>");
paging()

app/views/units/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Short Name</Data></Cell>
      </Row>
    <% Unit.all.each do |unit| %>
      <Row>
        <Cell><Data ss:Type="String"><%= unit.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= unit.short_name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/units/new.html.erb
<%= render partial: 'form', locals: {label: 'Add'} %>

app/views/units/show.html.erb
<script src="/js/jquery.min.js"></script><!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<div id="ribbon"><!-- RIBBON -->
  <ol class="breadcrumb"><!-- breadcrumb -->
    <li>Master Data</li><li>Unit</li><li><%= @unit.name %></li>
  </ol><!-- end breadcrumb -->
</div><!-- END RIBBON -->
<div id="content"><!-- MAIN CONTENT -->
  <div class="row">
    <article class="col-sm-12 col-md-12"><!-- NEW COL START -->
      <div class="jarviswidget" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
        <header id="header-supplier">
          <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
          <h2><%= @unit.name %></h2>
        </header>
        <div><!-- widget div-->
          <div class="widget-body no-padding"><!-- widget content -->
            <%= form_for @unit, html: {class: "smart-form", id: "form-update-verify"} do |f| %>
              <fieldset>
                <div class="row">
                  <section class="col col-md-6">
                    <section>
                      <label class="label col-md-3">Unit Name</label>
                      <label class="input col-md-9 custom-input-box"><%= @unit.name %></label>
                    </section>
                    <section>
                      <label class="label col-md-3">Abbreviation</label>
                      <label class="input col-md-9 custom-input-box"><%= @unit.short_name %></label>
                    </section>
                  </section>
                </div> <!-- row -->
              </fieldset>
              <footer>
                <button type="button" class="btn btn-default" onclick="window.history.back();">Back</button>
              </footer>
            <% end %>
          </div><!-- end widget content -->
        </div><!-- end widget div -->
      </div><!-- end widget -->
    </article><!-- END COL -->
  </div><!-- end widget div -->
</div><!-- end widget div -->

app/views/units/update.js.erb
$("#notification").html("<%= j(render 'dashboard/notification') %>");
<% if @unit.errors.blank? %>
  $("#unit-list").html("<%= j(render 'unit_list') %>");
<% end %>
$("#form-unit").html("<%= j(render 'form') %>");