config/routes.rb
      get :add_branch
      get :add_m_class
      get :autocomplete_goods_barcode
      get :mclass_per_department
      get :transaction_history
      post :import
    end
    member do
      get :print_to_pdf
      get :mutation_history
    end
  end

  resources :product_suppliers do
    collection do
      get :contact_people_per_supplier
      get :autocomplete_contact_person_name
      get :search_product_manual
    end
  end

  resources :edc_machines do
    collection do
      post :import
    end
  end
  resources :head_offices do
    collection do
      get :autocomplete_head_office_office_name
      get :branches_per_regional
      get :areas_per_branches
    end
  end

  resources :branches do
    collection do
      get :autocomplete_branch_office_name
      get :branches_per_regional
      get :areas_per_branches
      post :import
    end
  end

  resources :warehouses do
    collection do
      get :autocomplete_warehouse_office_name
      get :branches_per_regional
      get :areas_per_branches
    end
  end

  resources :vouchers
  resources :promos
  resources :stock_transfers do
    collection do
      get :search
      get :autocomplete_stock_transfer_name
      get :add_brand
      get :add_product
      get :get_last_number
    end
    member do
      get :print_to_pdf
    end
  end

  resources :planograms do
    resources :product_planograms
    collection do
      post :import
    end
  end

  resources :regionals do
    collection do
      post :import
      get :autocomplete_regional_name
    end
  end

  resources :cities do
    collection do
      post :import
      get :cities_per_regional
      get :autocomplete_city_name
    end
  end

  resources :areas do
    collection do
      post :import
      get :areas_per_cities
      get :branches_per_regional
      get :autocomplete_area_name
    end
  end

  resources :districts do
    collection do
      post :import
      get :autocomplete_districts_name
    end
  end

  resources :provinces do
    collection do
      post :import
      get :autocomplete_province_name
      get :provinces_per_regional
    end
  end

  resources :units do
    collection do
      get :autocomplete_unit_namepri
      post :import
    end
  end

  resources :price_tags do
    collection do
      get :print_to_pdf
      get :print_newest_product
      get :get_products_to_table
    end
    member do
      get :print_to_pdf
    end
  end

  resources :m_classes do
    collection do
      get :autocomplete_m_class_name
      get :add_sub_m_class
      post :import
    end
  end

  resources :product_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
      get :print_to_pdf
    end
    collection do
      get :add_product
    end
  end

  resources :product_transfer_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
    end
    collection do
      get :add_product
    end
  end

  resources :ads do
    collection do
      get :autocomplete_ad_url
      post :import
    end
  end
  resources :close_shifts do
    collection do
      get :tutup_shift
      get :save_income
      get :search_shift
    end
    member do
      get :print_to_pdf
    end
  end
  resources :month_ends do
    collection do
      get :report
    end
  end
  resources :colours do
    collection do
      get :autocomplete_colour_name
      post :import
    end
  end
  resources :planos do
    collection do
      get :autocomplete_plano_name
      get :get_planogram_type
      get :get_spd
      get :autogenerate_type
      get :generate_auto_pkm, as: 'generate_auto_pkm'
      post :import
    end
  end
  resources :pos_machines do
    collection do
      get :autocomplete_pos_machine_name
      post :import
    end
  end
  resources :selling_prices do
    collection do
      post :import
      get :search_product_manual
      get :search_in_modal
      get :fitur_filter
    end
  end
  resources :purchase_prices do
    collection do
      post :import
      get :search_product_manual
      get :search_in_modal
      get :fitur_filter
    end
  end

  resources :product_margins do
    collection do
      post :import
    end
  end

  resources :member_levels do
    collection do
      get :autocomplete_member_level_description
      post :import
    end
  end
  resources :to_do_lists do
    collection do
      post :import
    end
  end
  resources :promotions do
    collection do
      get :search
      get :autocomplete_promotion_name
      get :add_prize_list
      get :add_promo_item_list
      get :search_product_manual
      get :search_in_modal
      get :get_product
    end
  end

  resources :branch_prices

  resources :stock_opnames do
    collection do
      get :get_quantity_data
      get :start_stock_opname_data
      get :end_stock_opname_data
      get :select_stock_opname_data
      get :offices_per_rack
      get :rack_selected
    end
    member do
      get :print_to_pdf
      get :print_lkso
    end
  end

  resources :stock_opname_details do
    collection do
      post :import
    end
  end

  resources :members do
    collection do
      get :search
      get :discount
      post :create_member_discount
      post :import
      get '/edit_member_discount/:id' => 'members#edit_member_discount', as: :edit_member_discount
      put '/update_member_discount/:id' => 'members#update_member_discount', as: :update_member_discount
      delete '/delete_member_discount/:id' => 'members#delete_member_discount', as: :delete_member_discount
      put '/expired/:id' => 'members#expire', as: :expire
      get '/setting_point' => 'members#setting_point', as: :setting_point
      post 'create_setting_point' => 'members#create_setting_point', as: :create_setting_point
    end
  end

  resources :colours do
    collection do
      get :search
      get :autocomplete_colour_name
    end
  end

  resources :reorder_points do
    collection do
    end
  end

  resources :safety_stocks do
    collection do
    end
  end

  resources :out_stocks do
    collection do
      get :search
      get :autocomplete_out_stock_name
    end
  end

  resources :min_stocks do
    collection do
      get :search
      get :autocomplete_min_stock_name
    end
  end

  resources :price_histories do
    collection do
      get :search
    end
  end

  resources :good_transfers do
    member do
      get :print_to_pdf
    end
    collection do
      get :search
      get :autocomplete_good_transfer_code
      get :get_product
      get :add_brand
      get :add_product
      get :get_last_number
      get :get_template
      post :import
    end
  end

  resources :departments do
    collection do
      get :search
      get :autocomplete_department_name
      get :departments_per_supplier
      post :import
      get :departments_list
      get :categories_per_department
    end
  end

  resources :brands do
    collection do
      get :search
      get :autocomplete_brand_name
      post :import
      get :brands_per_supplier
      get :generate_data_brand
    end
  end

  resources :suppliers do
    collection do
      get :get_suppliers_modal
      get :search_supplier
      get :get_number
      get :search
      get :autocomplete_supplier_name
      get :autocomplete_supplier_code
      post :import
      get :add_contact
      get :add_bank_account
    end
  end

  resources :sizes do
    collection do
      get :search
      get :autocomplete_size_name
      get :generate_details
    end
  end

  resources :types do
    collection do
      get :search
      get :autocomplete_type_name
      get 'detail_sub_type/:id' => "types#detail_sub_type", as: :detail_sub_type
      get 'new_sub_type/:id' => "types#new_sub_type", as: :new_sub_type
    end
  end

  devise_for :users
  resources :users do
    collection do
      get :autocomplete_name
    end
    member do
      get :change_password
      patch :post_change_password
    end
  end
  resources :user_profiles do
    member do
      patch :update_profile
    end
  end

  resources :companyprofile do

  end

  resources :organizations do
    member do
      get :position_edit
    end
    collection do
      get :search
      get :posisision_data
      get :position_index
      post :position_index
      get :position_show
      get :position_new
      post :position_create
      delete :position_destroy
      patch :position_update
      put :position_update

    end
  end

   resources :positions

  resources :fingerprints do
    collection do
      get :search
    end
  end

  resources :companies do
    collection do
      get :get_city
    end
  end

  resources :roles do
    collection do
      post :import
    end
  end

  resources :approvals

  resources :asset_assignments do
    collection do
      post :return
    end
  end

  resources :recruitments

  resources :visions, only: [:index, :show] do
    collection do
      post :setup
      get :visi_misi
    end
  end

  resources :misions, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :cultures, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :code_of_conducts, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :values, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :holidays

  resources :personal_datas

  resources :holiday_types do
    collection do
      put :update_holiday_type
      get :search
    end
  end

  resources :shifts

  resources :knowledges do
    collection do
    	get :autocomplete_name
      get :knowledge_new
      get :search
      get :knowledge_show
      get :knowledge_new
      post :knowledge_create
      delete :knowledge_destroy
      get :knowledge_edit
      patch :knowledge_update
      put :knowledge_update
      post :dropzone
      get :dropzone

    end
  end

  resources :blast_messages do

app/models/colour.rb
class Colour < ActiveRecord::Base
#  include Filter
  JOIN = ''
  ORDER = 'colours.id'
  SELECTED = 'colours.*'
  GROUP_BY = 'colours.id'

  before_validation :upcase_save
  #before_destroy :goods_already_in_used?

  #has_many :goods, class_name: "Goods", dependent: :destroy

  validates :name, :presence => {message: 'required'} , :uniqueness => true
  validates_format_of :name, :with => /^[a-zA-Z\d\s]*$/i, :multiline => true, :message => "alphabet input only"

  scope :search, lambda {|search|{
    :order => "code ASC",
    :conditions => [
      'code LIKE ? OR name LIKE ?',
      "%#{search.first}%", "%#{search.first}%"
    ]
  }}

  def check_transaction
    return false if Product.find_by_colour_id(self.id) || Product.find_by_colour2_id(self.id) || Product.find_by_colour3_id(self.id) || Product.find_by_colour4_id(self.id)
    true
  end

  def upcase_save
    self.name = name.titleize rescue nil
  end
=begin
  def goods_already_in_used?
    return true
    #goods.each{|item|return false if item.check_relation}
  end
=end
  def self.number(params)
    number = (Colour.first(:conditions => "name like '#{params[:first_char]}%'", :order => "id DESC").code[1..-1].to_i rescue 0)+1
    return number
  end

  def self.create_number(params)
    init = params[:colour][:name][0]
    number = (Colour.first(:conditions => "name like '#{init}%'", :order => "id DESC").code[1..-1].to_i rescue 0)+1
    return number
  end

  def self.get_colour_id(colour)
    id = (Colour.first(:conditions => "code = '#{colour}' or name = '#{colour}'", :order => "id DESC").id.to_i rescue 0)
    return id
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ["code", "name"]
      all.each do |colour|
        csv << [colour.code, colour.name]
      end
    end
  end

  def self.to_csv2(options = {})
    CSV.generate(options) do |csv|
      csv << ["name"]
      all.each do |colour|
      end
    end
  end

  def self.import(file)
    line = 0
    CSV.foreach(file.path, headers: true) do |row|
      if find_by_name(row["name"].upcase).nil?
        parameters = ActionController::Parameters.new(row.to_hash)
        colour = new(parameters.permit(:name).merge(:code => "C#{('%03d' % ((Colour.last.code.gsub('C', '').to_i rescue 0)+1))}"))
        unless colour.save
          return {error: 1, message: line == 0 ? "Import failed, please recheck CSV file. #{colour.errors.full_messages.join('<br/>')}" : "Successfully imported until line #{line}. Failed imported  from line #{line+1}. Please recheck and reupload from line #{line+1}. #{colour.errors.full_messages.join('<br/>')}"}
        end
        line += 1
      else
        return {error: 0, message: "Successfully imported"}
      end
    end
    return {error: 0, message: "Successfully imported"}
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:destroy]
  autocomplete :colour, :name
  before_filter :can_view_colour, only: [:index, :show]
  before_filter :can_manage_colour, only: [:new, :create, :edit, :update]

  # GET /colours
  # GET /colours.json
  def index
    get_paginated_colours
    respond_to do |format|
      format.html
      format.js
      format.xls
      if(params[:a] == "a")
        format.csv { send_data Colour.all.to_csv2 }
      else
        format.csv { send_data Colour.all.to_csv }
      end
    end
  end

  def import
    import_result = Colour.import(params[:file])
    if params[:file].present?
      if import_result[:error] == 1
        flash[:error] = import_result[:message]
      else
        flash[:notice] = import_result[:message]
      end
    else
      flash[:error] = "Please attach CSV File"
    end
    redirect_to colours_path
  end

  def show
    @colour = Colour.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def new
    @colour = Colour.new(params[:colour])
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /colours/1/edit
  def edit
    @colour = Colour.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # POST /colours
  # POST /colours.json
  def create
    init = params[:colour][:name][0]
    colour_number = Colour.create_number(params)
    @colour = Colour.new(colour_params.merge(code: ("C#{('%03d' % ((Colour.last.code.gsub('C', '').to_i rescue 0)+1))}")))
    if @colour.save
      flash[:notice] = 'Colour was successfully created'
      redirect_to colours_path
    else
      flash[:error] = @colour.errors.full_messages.join('<br/>')
      render "new"
    end
  end

  # PUT /colours/1
  # PUT /colours/1.json
  def update
    @colour = Colour.find(params[:id])
    if @colour.update_attributes(colour_params)
      flash[:notice] = 'Colour was successfully created'
      redirect_to colours_path
    else
      flash[:error] = @colour.errors.full_messages.join('<br/>')
      # format.js
      render "edit"
    end
  end

  # DELETE /colours/1
  # DELETE /colours/1.json
  def destroy
    @colour = Colour.find(params[:id])
    if @colour.check_transaction && @colour.destroy
      flash[:error] = nil
      flash[:notice] = "Successfully delete colour"
    else
      flash[:notice] = nil
      flash[:error] = "Can't delete colour. data in used"
    end
    get_paginated_colours
    respond_to do |format|
      format.js
    end
  end

  def search
    @colours = Colour.search(params[:search]).uniq.paginate(:page => params[:page], :per_page => 10) || []
    respond_to do |format|
      @colour = Colour.new
      format.js
    end
  end

  def get_number
    @colour_number = Colour.number(params)
    respond_to do |format|
      format.js
    end
  end

  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

private
  def colour_params
    params.require(:colour).permit(:code, :name)
  end

  def can_view_colour
    not_authorized unless current_user.can_view_colour?
  end

  def can_manage_colour
    not_authorized unless current_user.can_manage_colour?
  end
end

app/views/colours/_colour_list.html.erb
<% @colours.each_with_index do |colour, i| %>
  <tr>
    <td class="hidden-phone"><%= params[:page] ? (params[:page].to_i*10+i-9) : i+1 %></td>
    <td><span class="name"><%= colour.code %></span></td>
    <td><%= link_to colour.name, colour_path(colour), class: 'blue' %></td>
    <td class="hidden-phone">
      <%= link_to edit_colour_path(colour), class: "btn btn-primary btn-xs" do %>
        <i class="fa fa-pencil"></i>
      <% end %>
      <%= link_to 'javascript:void(0)', onclick: "delete_one(#{colour.id}, 'colours')", class: "btn btn-danger btn-xs" do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
    </td>
  </tr>
<% end %>
<tr>
  <td colspan=4>
    <% if @colours.present? %>
      <div class="dataTables_paginate paging_simple_numbers" id="dt_basic_paginate">
        <%= pagination_links(@colours, options = {}) %>
      </div>
    <% else %>
      <%= raw '<center>No Data Available</center>' %>
    <% end %>
  </td>
</tr>

app/views/colours/_form.html.erb
<div id="ribbon"><!-- RIBBON -->
  <ol class="breadcrumb"><!-- breadcrumb -->
    <li>Master Data</li><li>Colour</li><li><%= label %></li>
  </ol><!-- end breadcrumb -->
</div><!-- END RIBBON -->
<div id="content"><!-- MAIN CONTENT -->
  <div class="row">
    <article class="col-sm-12 col-md-12"><!-- NEW COL START -->
      <div class="jarviswidget" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
        <header id="header-colour">
          <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
          <h2><%= label %> Colour</h2>
        </header>
        <div><!-- widget div-->
          <div class="widget-body no-padding"><!-- widget content -->
            <%= form_for @colour, html: {class: "smart-form", id: "form-update-verify", :autocomplete => "off"} do |f| %>
              <fieldset>
                <div class="row">
                  <section class="col col-md-6">

                    <section>
                      <label class="col-md-2 label">Code</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= f.text_field :code, class: "input-sm #{(error_field @colour, :code)}", :placeholder => "Auto Generate", disabled: true %>
                      </label>
                    </section>
                    <section>
                      <label class="col-md-2 label">Name <span class='important'>*</span></label>
                      <label class="col-md-9 input custom-input-box"><%= f.text_field :name, :class => "input-sm #{(error_field @colour, :name)}" %></label>
                    </section>

                  </section> <!-- col-md-12 -->
                </div> <!-- row -->
              </fieldset>
              <footer>
                <button type="submit" class="btn btn-primary">
                  Submit
                </button>
                <button type="button" class="btn btn-default" onclick="window.history.back();">
                  Back
                </button>
              </footer>
            <% end %>
          </div><!-- end widget content -->
        </div><!-- end widget div -->
      </div><!-- end widget -->
    </article><!-- END COL -->
  </div><!-- end widget div -->
</div><!-- end widget div -->

app/views/colours/create.js.erb
$("#notification").html("<%= j(render 'dashboard/notification') %>");
	$("#colour-list").html("<%= j(render 'colour_list') %>");
$("#form-colour").html("<%= j(render 'form') %>");

app/views/colours/destroy.js.erb
$("#colour-list").html("<%= j(render 'colour_list') %>");
paging()
$("#notice_template").html("<%= j(render 'layouts/notice') %>");

app/views/colours/edit.html.erb
<%= render partial: 'form', locals: {label: 'Edit'} %>

app/views/colours/edit.js.erb
$("#form-colour").html("<%= j(render 'form') %>");

app/views/colours/get_number.js.erb
$('#colour_code').val('<%= "#{params[:first_char]}#{@colour_number}" %>')

app/views/colours/index.html.erb
<link rel="stylesheet" href="/css/jquery-ui-1.11.4.css">
<script src="/js/jquery-1.10.2.js"></script>
<script src="/js/jquery-ui-1.11.4.js"></script>
<div id="ribbon">
  <ol class="breadcrumb">
    <li><%= t(:data_master) %></li><li><%= t(:colour) %></li><li><%= t(:list) %></li>
  </ol>
</div>
<div id="content">
  <section id="widget-grid" class="">
    <div id="notice_template"><%= render 'layouts/notice' %></div>
    <div class="row">
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-1" data-widget-editbutton="false"><!-- Widget ID (each widget will need unique ID)-->
          <header id="header-product" role="heading">
          <h2><span class="widget-icon"> <i class="fa fa-list-ul"></i> </span> <%= t(:colour_list) %></h2> <!-- header content --></header>
          <div>
            <div class="widget-body no-padding">
              <%= link_to raw("<span class='btn-label'><i class='glyphicon glyphicon-plus'></i></span>#{t(:add_colour)}"), new_colour_url,
                class: "btn btn-labeled btn-primary edit-btn-primary" %>
              <ul id="myTab1" class="nav nav-tabs" style='margin: 20px 0 6px 6px; float: left'>
                <li class="dropdown">
                  <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i></button>
                  <ul class="dropdown-menu">
                    <li><%= link_to t(:export_to_csv), colours_path(:id => params[:id], format: "csv") %></li>
                    <li><%= link_to t(:export_to_excel), colours_path(:id => params[:id], format: "xls") %></li>
                    <li data-toggle="modal" data-target="#myModal" style='cursor: pointer'><a>Import from CSV</a></li>
                  </ul>
                </li>
              </ul>
            </div>
            <table class="table table-striped table-bordered" width="100%">
              <thead>
                <tr>
                  <th><%= t(:no) %></th>
                  <th>
                    <%= t(:code) %>
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'code-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'code-asc', class: 'sorting' %>
                    </span>
                  </th>
                  <th>
                    <%= t(:colour_name) %>
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'name-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'name-asc', class: 'sorting' %>
                    </span>
                    </th>
                    <th class="col-md-2"><%= t(:action) %></th>
                  </tr>
                  <tr>
                    <th></th>
                    <th class="hasinput"><%= text_field_tag :code, params[:code], class: 'form-control search' %></th>
                    <th class="hasinput"><%= text_field_tag :name, params[:name], class: 'form-control search' %></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody id='colour-list'><%= render 'colour_list' %></tbody>
              </table>
            </div>
          </div>
      </article>
    </div>
  </section>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Import Colour</h4>
      </div>
      <%= form_tag import_colours_path(:id => params[:id]), multipart: true do %>
        <div class="modal-body">
          <%= file_field_tag :file, accept: ".csv", onchange: "checkfile(this);" %>
        </div>
        <div class="modal-footer">
          <%= link_to "Download Template", colours_path(format: "csv", :a => "a"), :class => "btn btn-success" %>
          <%= submit_tag "Import", :class => "btn btn-primary", :id => 'commit'%>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $('#commit').bind("click",function(){ 
    if(!$('#file').val()){
      alert("File not been chosen");
      return false;
    }
  }); 
  window.reset = function (e) {
    e.wrap('<form>').closest('form').get(0).reset();
    e.unwrap();
  }
});
function checkfile(sender) {
    var validExts = new Array(".csv");
    var fileExt = sender.value;
    fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
    if (validExts.indexOf(fileExt) < 0) {
      alert("This is not a csv file");
      reset($("#file"));
      return false;
    }
    else return true;
};
</script>

app/views/colours/index.js.erb
$("#colour-list").html("<%= j(render 'colour_list') %>");
paging()

app/views/colours/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Product Detail Id</Data></Cell>
        <Cell><Data ss:Type="String">Stock</Data></Cell>
        <Cell><Data ss:Type="String">Stock Type</Data></Cell>
      </Row>
    <% ProductStock.all.each do |colour| %>
      <Row>
        <Cell><Data ss:Type="String"><%= productstock.code %></Data></Cell>
        <Cell><Data ss:Type="String"><%= productstock.name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/colours/new.html.erb
<%= render partial: 'form', locals: {label: t(:add)} %>

app/views/colours/search.js.erb
$("#colour-list").html("<%= j(render 'colour_list') %>");
$("#form-colour").html("<%= j(render 'form') %>");

app/views/colours/show.html.erb
<script src="/js/jquery-2.1.1.min.js"></script><!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<div id="ribbon"><!-- RIBBON -->
  <ol class="breadcrumb"><!-- breadcrumb -->
    <li>Master Data</li><li>Colour</li><li><%= @colour.name %></li>
  </ol><!-- end breadcrumb -->
</div><!-- END RIBBON -->
<div id="content"><!-- MAIN CONTENT -->
  <div class="row">
    <article class="col-sm-12 col-md-12"><!-- NEW COL START -->
      <div class="jarviswidget" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
        <header id="header-supplier">
          <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
          <h2><%= @colour.name %></h2>
        </header>
        <div><!-- widget div-->
          <div class="widget-body no-padding"><!-- widget content -->
            <%= form_for @colour, html: {class: "smart-form", id: "form-update-verify"} do |f| %>
              <fieldset>
                <div class="row">
                  <section class="col col-md-6">
                    <section>
                      <label class="col-md-2 label">Code</label>
                      <label class="col-md-9 input custom-input-box">
                        <%= @colour.code %>
                      </label>
                    </section>
                    <section>
                      <label class="col-md-2 label">Name</label>
                      <label class="col-md-9 input custom-input-box"><%= @colour.name %></label>
                    </section>
                  </section> <!-- col-md-12 -->
                </div> <!-- row -->
              </fieldset>
              <footer>
                <button type="button" class="btn btn-default" onclick="window.history.back();">Back</button>
              </footer>
            <% end %>
          </div><!-- end widget content -->
        </div><!-- end widget div -->
      </div><!-- end widget -->
    </article><!-- END COL -->
  </div><!-- end widget div -->
</div><!-- end widget div -->

app/views/colours/update.js.erb
$("#notification").html("<%= j(render 'dashboard/notification') %>");
<% if @supplier.errors.blank? %>
	$("#colour-list").html("<%= j(render 'colour_list') %>");
<% end %>
$("#form-colour").html("<%= j(render 'form') %>");